backend:
  name: github
  repo: caseykey/caseykey.github.io
  branch: master
  site_domain: quirky-bassi-7f760a.netlify.com

media_folder: "images/uploads"

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "src/data/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Project Name", name: "project", widget: "string"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Icons", name: "icons", widget: "list"}
      - {label: "Description", name: "description", widget: "markdown"}
